final List<Map<String, dynamic>> maps = [
  {"map": "S5_1/Levels/MP/Geonosis_01/Geonosis_01", "name": "Geonosis"},
  {"map": "S6_2/Geonosis_02/Levels/Geonosis_02/Geonosis_02", "name": "Geonosis"},
  {"map": "Levels/MP/Kamino_01/Kamino_01", "name": "Kamino"},
  {"map": "S7_1/Levels/Kamino_03/Kamino_03", "name": "Kamino"},
  {"map": "Levels/MP/Naboo_01/Naboo_01", "name": "Naboo"},
  {"map": "Levels/MP/Naboo_02/Naboo_02", "name": "Naboo"},
  {"map": "S7_2/Levels/Naboo_03/Naboo_03", "name": "Naboo"},
  {"map": "Levels/MP/Kashyyyk_01/Kashyyyk_01", "name": "Kashyyyk"},
  {"map": "S7/Levels/Kashyyyk_02/Kashyyyk_02", "name": "Kashyyyk"},
  {"map": "S8/Felucia/Levels/MP/Felucia_01/Felucia_01", "name": "Felucia"},
  {"map": "S3/Levels/Kessel_01/Kessel_01", "name": "Kessel"},
  {"map": "S9_3/Scarif/Levels/MP/Scarif_02/Scarif_02", "name": "Scarif"},
  {"map": "Levels/MP/Tatooine_01/Tatooine_01", "name": "Tatooine"},
  {"map": "S9_3/Tatooine_02/Tatooine_02", "name": "Tatooine"},
  {"map": "Levels/MP/Yavin_01/Yavin_01", "name": "Yavin"},
  {"map": "Levels/MP/Hoth_01/Hoth_01", "name": "Hoth"},
  {"map": "S9_3/Hoth_02/Hoth_02", "name": "Hoth"},
  {"map": "S2/Levels/CloudCity_01/CloudCity_01", "name": "Bespin"},
  {"map": "S2_2/Levels/JabbasPalace_01/JabbasPalace_01", "name": "Tatooine"},
  {"map": "Levels/MP/Endor_01/Endor_01", "name": "Endor"},
  {"map": "S2_1/Levels/Endor_02/Endor_02", "name": "Endor - Ewok Village"},
  {"map": "S8_1/Endor_04/Endor_04", "name": "Endor - Research Station 9"},
  {"map": "Levels/MP/DeathStar02_01/DeathStar02_01", "name": "Death Star II"},
  {"map": "Levels/MP/Jakku_01/Jakku_01", "name": "Jakku"},
  {"map": "S9/Jakku_02/Jakku_02", "name": "Jakku"},
  {"map": "Levels/MP/Takodana_01/Takodana_01", "name": "Takodana"},
  {"map": "S9/Takodana_02/Takodana_02", "name": "Takodana"},
  {"map": "Levels/MP/StarKiller_01/StarKiller_01", "name": "Starkiller Base"},
  {"map": "S9/StarKiller_02/StarKiller_02", "name": "Starkiller Base"},
  {"map": "S1/Levels/Crait_01/Crait_01", "name": "Crait"},
  {"map": "S9_3/Crait/Crait_02", "name": "Crait"},
  {"map": "S9/Paintball/Levels/MP/Paintball_01/Paintball_01", "name": "Ajan Kloss"},
  {"map": "S9_3/COOP_NT_MC85/COOP_NT_MC85", "name": "MC85 Star Cruiser"},
  {"map": "S9_3/COOP_NT_FOSD/COOP_NT_FOSD", "name": "First Order Star Destroyer"},
  {"map": "Levels/Space/SB_DroidBattleShip_01/SB_DroidBattleShip_01", "name": "Ryloth"},
  {"map": "Levels/Space/SB_Kamino_01/SB_Kamino_01", "name": "Kamino"},
  {"map": "Levels/Space/SB_Fondor_01/SB_Fondor_01", "name": "Fondor"},
  {"map": "Levels/Space/SB_Endor_01/SB_Endor_01", "name": "Endor"},
  {"map": "Levels/Space/SB_Resurgent_01/SB_Resurgent_01", "name": "Unknown Regions"},
  {"map": "S1/Levels/Space/SB_SpaceBear_01/SB_SpaceBear_01", "name": "D'Qar"}
];
